#!/bin/zsh

set -e

srcpath=$(cat srcpath)

typeset -a hosts
hosts=(c6n1.gbif.org
c6n2.gbif.org
c6n3.gbif.org
c6n4.gbif.org
c6n5.gbif.org
c6n6.gbif.org
c6n7.gbif.org
c6n8.gbif.org
c6n9.gbif.org)

for h in $hosts; do
    ssh mblissett@$h w
done

x=0
for i j k l m n o p q r s t in ??????_0; do
    h=$hosts[$(($x % $#hosts + 1))]
    echo $h $i $j $k $l $m $n $o $p $q $r $s $t
    /usr/bin/ssh mblissett@$h nice -n 20 java -jar ~/parquet-testing-1.0-SNAPSHOT-jar-with-dependencies.jar $srcpath/$i $srcpath/$j $srcpath/$k $srcpath/$l $srcpath/$m $srcpath/$n $srcpath/$o $srcpath/$p $srcpath/$q $srcpath/$r $srcpath/$s $srcpath/$t &
    rm -f $i $j $k $l $m $n $o $p $q $r $s $t
    x=$((x + 1))
    if [[ $x = $#hosts ]]; then
        exit 0
    fi
    sleep 0.2
done

exit
