#!/bin/zsh

set -e

srcpath=$(cat srcpath)

ssh mblissett@$1 w

for i in ??????_0; do
    echo $1 $i
    /usr/bin/ssh mblissett@$1 nice -n 20 java -jar ~/parquet-testing-1.0-SNAPSHOT-jar-with-dependencies.jar $srcpath/$i &
    rm -f $i
    exit 0
done
